-- SQL syntax for inserts

-- table 1 - facilities
INSERT INTO facilities (facilities_type) values ('Cryotherapy Chamber');
INSERT INTO facilities (facilities_type) VALUES ('Hyperbaric Oxygen Chamber');
INSERT INTO facilities (facilities_type) VALUES ('Indoor Rock Climbing Wall');
INSERT INTO facilities (facilities_type) VALUES ('Ninja Warrior Obstacle Course');
INSERT INTO facilities (facilities_type) VALUES ('Aerial Silks Studio');
INSERT INTO facilities (facilities_type) VALUES ('Floating Sensory Deprivation Tanks');
INSERT INTO facilities (facilities_type) VALUES ('Bouldering Wall');
INSERT INTO facilities (facilities_type) VALUES ('Anti-Gravity Treadmill');
INSERT INTO facilities (facilities_type) VALUES ('Infrared Sauna Pods');
INSERT INTO facilities (facilities_type) VALUES ('Virtual Reality Fitness Stations');
INSERT INTO facilities (facilities_type) VALUES ('Hypoxic Training Room (Simulated Altitude)');
INSERT INTO facilities (facilities_type) VALUES ('Aquatic Treadmills (Underwater Treadmills)');
INSERT INTO facilities (facilities_type) VALUES ('Aqua Cycling Pool');
INSERT INTO facilities (facilities_type) VALUES ('Biomechanics Lab');
INSERT INTO facilities (facilities_type) VALUES ('Gravity Resistance Training System');
INSERT INTO facilities (facilities_type) VALUES ('Electro Muscle Stimulation (EMS) Training');
INSERT INTO facilities (facilities_type) VALUES ('Mind-Body Meditation Pods');
INSERT INTO facilities (facilities_type) VALUES ('Biosensing Wearable Technology');
INSERT INTO facilities (facilities_type) VALUES ('Dynamic Resistance Technology');
INSERT INTO facilities (facilities_type) VALUES ('Kinesis Wall (Multi-Functional Movement Station)');
INSERT INTO facilities (facilities_type) VALUES ('Exergaming Zone (Interactive Fitness Games)');
INSERT INTO facilities (facilities_type) VALUES ('Acrobatic Yoga Facilities');
INSERT INTO facilities (facilities_type) VALUES ('Biosauna (Combining Biofeedback with Sauna)');
INSERT INTO facilities (facilities_type) VALUES ('Outdoor Calisthenics Park');
INSERT INTO facilities (facilities_type) VALUES ('Holographic Personal Trainer');
INSERT INTO facilities (facilities_type) VALUES ('Kinetic Energy-Harvesting Equipment');
INSERT INTO facilities (facilities_type) VALUES ('Rebounder Mini-Trampoline Area');
INSERT INTO facilities (facilities_type) VALUES ('Aromatherapy and Wellness Lounge');
INSERT INTO facilities (facilities_type) VALUES ('Parkour Training Space');
INSERT INTO facilities (facilities_type) VALUES ('Hiking/Trail Running Paths');
INSERT INTO facilities (facilities_type) VALUES ('Magnetic Resonance Therapy');
INSERT INTO facilities (facilities_type) VALUES ('AI-Powered Adaptive Training Programs');
INSERT INTO facilities (facilities_type) VALUES ('Mindful Movement Lab');
INSERT INTO facilities (facilities_type) VALUES ('Recovery Boots Stations');
INSERT INTO facilities (facilities_type) VALUES ('Hydration Stations with Infused Water');
INSERT INTO facilities (facilities_type) VALUES ('Neurofeedback Training Stations');
INSERT INTO facilities (facilities_type) VALUES ('Zorbing Ball Fitness');
INSERT INTO facilities (facilities_type) VALUES ('Brain-Computer Interface (BCI) Workouts');
INSERT INTO facilities (facilities_type) VALUES ('Climbing Rope Stations');
INSERT INTO facilities (facilities_type) VALUES ('Inversion Therapy Tables');
INSERT INTO facilities (facilities_type) VALUES ('Sensory Integration Room');
INSERT INTO facilities (facilities_type) VALUES ('Thermal Imaging for Muscle Activation');
INSERT INTO facilities (facilities_type) VALUES ('Solar-Powered Workout Stations');
INSERT INTO facilities (facilities_type) VALUES ('Energy-Generating Cardio Equipment');
INSERT INTO facilities (facilities_type) VALUES ('Gyrotonic Expansion System');
INSERT INTO facilities (facilities_type) VALUES ('Bike-Powered Charging Stations');
INSERT INTO facilities (facilities_type) VALUES ('Vibration Plate Training');
INSERT INTO facilities (facilities_type) VALUES ('Kinetic Sand Training Area');
INSERT INTO facilities (facilities_type) VALUES ('Aqua Bag Training Zone');
INSERT INTO facilities (facilities_type) VALUES ('Aerial Hammock Yoga Space');

-- table 2 - gyms
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('BodyShapeGym', 'Bulevardul Unirii 45, Timișoara', 2019, 'http://www.bodyshapegym.net', '731234567');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('EnergymFitnessClub', 'Calea Dorobanților 87, Cluj-Napoca', 1997, 'http://www.energymfitnessclub.com', '741345678');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('AmaltTraining', 'Strada Mihai Eminescu 23, Iași', 2010, 'http://www.amalttraining.org', '751456789');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('BodyTime', 'Bulevardul 1 Decembrie 1918 56, Brașov', 2016, 'http://www.bodytime-gym.com', '761567890');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('ClubFloreasca', 'Strada Avram Iancu 34, Constanța', 2002, 'http://www.clubfloreasca.ro', '771678901');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('DairyFit', 'Aleea Trandafirilor 9, Craiova', 2018, 'http://www.dairyfit-fitness.com', '781989012');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('DumsilGYM', 'Bulevardul Decebal 78, Galați', 2005, 'http://www.dumsilgym.eu', '791890123');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('EnergiaFitnessCenter', 'Strada Aurel Vlaicu 2, Ploiești', 2015, 'http://www.energiafitnesscenter.com', '701901234');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('Fitclass', 'Bulevardul Republicii 101, Oradea', 1999, 'http://www.fitclass-gym.com', '731012345');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('GecoFitnessClub', 'Calea Aradului 67, Bacău', 2006, 'http://www.gecofitnessclub.net', '741123456');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('GriffGym', 'Strada Revoluției 5, Arad', 2012, 'http://www.griffgym.com', '751234567');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('LibertyGym', 'Bulevardul Mihail Kogălniceanu 30, Sibiu', 2003, 'http://www.libertygym-fitness.com', '761345678');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('MeiyoGym', 'Strada Ion Creangă 17, Brăila', 2011, 'http://www.meiyogym.com', '771456789');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('NewFitWay', 'Aleea Soarelui 8, Baia Mare', 1998, 'http://www.newfitway-gym.com', '781567890');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('PTStudio', 'Calea Feldioarei 43, Buzău', 2007, 'http://www.ptstudio-fit.com', '791678901');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('PureShapes', 'Strada Ștefan cel Mare 21, Satu Mare', 2014, 'http://www.pureshapes-fitness.com', '701789012');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('SocialGym', 'Bulevardul Traian 11, Drobeta-Turnu Severin', 2004, 'http://www.socialgym.net', '731890123');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('SanaVivendi', 'Strada Cuza Vodă 14, Suceava', 2021, 'http://www.sanavivendi-gym.com', '741901234');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('VivaSport', 'Aleea Ghioceilor 3, Târgu Mureș', 2012, 'http://www.vivasport-fitness.com', '751012345');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('SASGym', 'Bulevardul Iuliu Maniu 19, Focșani', 1998, 'http://www.sasgym.com', '761123456');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('WestlifeFitness&Aerobic', 'Strada Vasile Alecsandri 25, Pitești', 2007, 'http://www.westlifefitnessaerobic.org', '771234567');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('WorldGymAcademy', 'Strada 22 Decembrie 1989 4, Tulcea', 2014, 'http://www.worldgymacademy.com', '781345678');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('BambooFitness', 'Aleea Magnoliei 7, Resita', 2003, 'http://www.bamboofitness-gym.com', '791456789');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('IzoconFitnessGym', 'Bulevardul Carol I 12, Deva', 2002, 'http://www.izoconfitnessgym.net', '701567890');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('Lady’sGym', 'Strada Calea Victoriei 3, Medgidia', 2005, 'http://www.ladysgym.com', '731678901');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('BigFitness', 'Calea Crângului 40, Bistrița', 2011, 'http://www.bigfitness-gym.com', '741789012');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('RealBodyGym', 'Strada Aviatorilor 9, Zalău', 2007, 'http://www.realbodygym.com', '75189023');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('EletroGYM', 'Bulevardul Eroilor 22, Slobozia', 2014, 'http://www.eletrogym.com', '761901234');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('FitnessClubRelaxsim', 'Strada Alexandru Sahia 14, Piatra Neamț', 2003, 'http://www.fitnessclubrelaxsim.org', '771012345');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('MelodyBodySculpture', 'Calea Timișoarei 76, Călărași', 2002, 'http://www.melodybodysculpture-gym.com', '781123456');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('Piti’sCenter', 'Strada Mihai Bravu 18, Tecuci', 2005, 'http://www.pitiscenter.com', '791234567');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('LIONSGYM', 'Bulevardul Ștefan cel Mare și Sfânt 14, Odorheiu Secuiesc', 2011, 'http://www.lionsgym.com', '701345678');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('AresGymFortuna', 'Strada Pictor Nicolae Grigorescu 4, Mangalia', 2000, 'http://www.aresgymfortuna.net', '731456789');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('TonicGym', 'Bulevardul Nicolae Bălcescu 2, Slatina', 2015, 'http://www.tonicgym-gym.com', '741567890');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('Lady’sFitGym', 'Calea Clujului 92, Alba Iulia', 1997, 'http://www.ladysfitgym.com', '751678901');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('ColosseumLady’s', 'Strada Mărășești 31, Giurgiu', 2019, 'http://www.colosseumladys.com', '761789012');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('BodyClubCasanova', 'Strada Alexandru Sahia 14, Piatra Neamț', 2006, 'http://www.bodyclubcasanova-gym.com', '771890123');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('C.S.ProFitnessVulcan', 'Calea Timișoarei 76, Călărași', 2012, 'http://www.csprofitnessvulcan.com', '781901234');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('JadeGym', 'Strada Mihai Bravu 18, Tecuci', 2003, 'http://www.jadegym.com', '791012345');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('FlexGym', 'Bulevardul Corneliu Coposu 5, Sighetu Marmației', 2011, 'http://www.flexgym-gym.com', '701123456');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('PerfectFit', 'Aleea Trifoiului 11, Vaslui', 2000, 'http://www.perfectfit-fitness.com', '731234567');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('ClubBlackKnightSquash&FitnessPloiesti', 'Strada Pictor Nicolae Grigorescu 4, Mangalia', 2005, 'http://www.clubblackknightploiesti.com', '741345678');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('GreenDiamond', 'Calea Rahovei 29, Adjud', 2011, 'http://www.greendiamond-fitness.com', '751456789');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('4UFitnessCenter', 'Strada Nicolae Titulescu 8, Lugoj', 2000, 'http://www.4ufitnesscenter.com', '761567890');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('SportCenter', 'Bulevardul Ștefan cel Mare și Sfânt 14, Odorheiu Secuiesc', 2015, 'http://www.sportcenter-gym.com', '771678901');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('SmartFitStudio', 'Strada George Coșbuc 7, Săcele', 1997, 'http://www.smartfitstudio.net', '781789012');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('FitnessModelGym', 'Aleea Bradului 16, Gherla', 2006, 'http://www.fitnessmodelgym.com', '791890123');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('HardcoreFitness', 'Calea Rahovei 29, Adjud', 2012, 'http://www.hardcorefitness-gym.com', '709901234');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('GymOne', 'Strada Nicolae Titulescu 8, Lugoj', 2003, 'http://www.gymone-fitness.com', '731012345');
INSERT INTO gym (name, address, year, website, contact_number) VALUES ('WorldClass', 'Bulevardul Ștefan cel Mare și Sfânt 14, Odorheiu Secuiesc', 2011, 'http://www.worldclass.com', '741123456');

-- table 3 - trainers
INSERT INTO trainer (name, age, experience_years, email, contact_number) VALUES ('Fabian Besca','22','5','weidmendingo@gmail.com','727619714');
INSERT INTO trainer (name, age, experience_years, email, contact_number) VALUES ('Alexandra Radu', '28', '12', 'alex.radu@gmail.com', '723456789');
INSERT INTO trainer (name, age, experience_years, email, contact_number) VALUES ('Marius Ionescu', '35', '8', 'marius.ionescu@outlook.com', '734567890');
INSERT INTO trainer (name, age, experience_years, email, contact_number) VALUES ('Elena Popa', '30', '15', 'elena.popa@yahoo.com', '745678901');
INSERT INTO trainer (name, age, experience_years, email, contact_number) VALUES ('Andrei Dima', '26', '3', 'andrei.dima@gmail.com', '756789012');
INSERT INTO trainer (name, age, experience_years, email, contact_number) VALUES ('Cristina Tudor', '31', '20', 'cristina.tudor@hotmail.com', '767890123');
INSERT INTO trainer (name, age, experience_years, email, contact_number) VALUES ('Ionut Stan', '27', '7', 'ionut.stan@yahoo.com', '778901234');
INSERT INTO trainer (name, age, experience_years, email, contact_number) VALUES ('Roxana Matei', '29', '18', 'roxana.matei@gmail.com', '789012345');
INSERT INTO trainer (name, age, experience_years, email, contact_number) VALUES ('Mihai Vasile', '32', '9', 'mihai.vasile@hotmail.com', '700123456');
INSERT INTO trainer (name, age, experience_years, email, contact_number) VALUES ('Gabriela Andrei', '33', '11', 'gabriela.andrei@yahoo.com', '711234567');
INSERT INTO trainer (name, age, experience_years, email, contact_number) VALUES ('Florin Radulescu', '25', '6', 'florin.radulescu@gmail.com', '722345678');
INSERT INTO trainer (name, age, experience_years, email, contact_number) VALUES ('Ana Dumitru', '34', '25', 'ana.dumitru@hotmail.com', '733456789');
INSERT INTO trainer (name, age, experience_years, email, contact_number) VALUES ('Sorin Popescu', '23', '14', 'sorin.popescu@yahoo.com', '744567890');
INSERT INTO trainer (name, age, experience_years, email, contact_number) VALUES ('Mihaela Iancu', '36', '2', 'mihaela.iancu@gmail.com', '755678901');
INSERT INTO trainer (name, age, experience_years, email, contact_number) VALUES ('Adrian Moldovan', '28', '19', 'adrian.moldovan@hotmail.com', '766789012');
INSERT INTO trainer (name, age, experience_years, email, contact_number) VALUES ('Andreea Neagu', '30', '4', 'andreea.neagu@yahoo.com', '777901234');
INSERT INTO trainer (name, age, experience_years, email, contact_number) VALUES ('Dorin Ionita', '31', '13', 'dorin.ionita@hotmail.com', '788012345');
INSERT INTO trainer (name, age, experience_years, email, contact_number) VALUES ('Raluca Balan', '27', '22', 'raluca.balan@gmail.com', '799123456');
INSERT INTO trainer (name, age, experience_years, email, contact_number) VALUES ('Catalin Marin', '35', '10', 'catalin.marin@hotmail.com', '710234567');
INSERT INTO trainer (name, age, experience_years, email, contact_number) VALUES ('Simona Stancu', '29', '16', 'simona.stancu@gmail.com', '721345678');
INSERT INTO trainer (name, age, experience_years, email, contact_number) VALUES ('Paul Ion', '26', '5', 'paul.ion@hotmail.com', '732456789');
INSERT INTO trainer (name, age, experience_years, email, contact_number) VALUES ('Anda Munteanu', '32', '23', 'anda.munteanu@yahoo.com', '743567890');
INSERT INTO trainer (name, age, experience_years, email, contact_number) VALUES ('Mariana Vasiliu', '33', '17', 'mariana.vasiliu@gmail.com', '754678901');
INSERT INTO trainer (name, age, experience_years, email, contact_number) VALUES ('George Gheorghe', '25', '8', 'george.gheorghe@hotmail.com', '765789012');
INSERT INTO trainer (name, age, experience_years, email, contact_number) VALUES ('Elena Stoica', '34', '12', 'elena.stoica@yahoo.com', '776901234');
INSERT INTO trainer (name, age, experience_years, email, contact_number) VALUES ('Ionel Popovici', '27', '15', 'ionel.popovici@hotmail.com', '787012345');
INSERT INTO trainer (name, age, experience_years, email, contact_number) VALUES ('Andrada Istrate', '28', '9', 'andrada.istrate@yahoo.com', '798123456');
INSERT INTO trainer (name, age, experience_years, email, contact_number) VALUES ('Valentin Cojocaru', '30', '7', 'valentin.cojocaru@hotmail.com', '709234567');
INSERT INTO trainer (name, age, experience_years, email, contact_number) VALUES ('Anca Serban', '31', '20', 'anca.serban@gmail.com', '720345678');
INSERT INTO trainer (name, age, experience_years, email, contact_number) VALUES ('Gabriel Marin', '26', '3', 'gabriel.marin@hotmail.com', '731456789');
INSERT INTO trainer (name, age, experience_years, email, contact_number) VALUES ('Larisa Dumitrache', '35', '14', 'larisa.dumitrache@yahoo.com', '742567890');
INSERT INTO trainer (name, age, experience_years, email, contact_number) VALUES ('Radu Ciocan', '29', '11', 'radu.ciocan@hotmail.com', '753678901');
INSERT INTO trainer (name, age, experience_years, email, contact_number) VALUES ('Mirela Coman', '32', '5', 'mirela.coman@yahoo.com', '764789012');
INSERT INTO trainer (name, age, experience_years, email, contact_number) VALUES ('Stefan Munteanu', '33', '18', 'stefan.munteanu@hotmail.com', '775901234');
INSERT INTO trainer (name, age, experience_years, email, contact_number) VALUES ('Bianca Vasilescu', '27', '13', 'bianca.vasilescu@gmail.com', '786012345');
INSERT INTO trainer (name, age, experience_years, email, contact_number) VALUES ('Ciprian Stanescu', '34', '22', 'ciprian.stanescu@outlook.com', '797123456');
INSERT INTO trainer (name, age, experience_years, email, contact_number) VALUES ('Monica Radulescu', '28', '6', 'monica.radulescu@yahoo.com', '708234567');
INSERT INTO trainer (name, age, experience_years, email, contact_number) VALUES ('Victor Toma', '30', '19', 'victor.toma@gmail.com', '719345678');
INSERT INTO trainer (name, age, experience_years, email, contact_number) VALUES ('Elena Grigorescu', '31', '8', 'elena.grigorescu@outlook.com', '730456789');
INSERT INTO trainer (name, age, experience_years, email, contact_number) VALUES ('Dragos Ion', '25', '16', 'dragos.ion@gmail.com', '741567890');
INSERT INTO trainer (name, age, experience_years, email, contact_number) VALUES ('Georgiana Dumitru', '32', '10', 'georgiana.dumitru@outlook.com', '752678901');
INSERT INTO trainer (name, age, experience_years, email, contact_number) VALUES ('Razvan Popa', '33', '7', 'razvan.popa@yahoo.com', '763789012');
INSERT INTO trainer (name, age, experience_years, email, contact_number) VALUES ('Andreea Costin', '26', '14', 'andreea.costin@gmail.com', '774901234');
INSERT INTO trainer (name, age, experience_years, email, contact_number) VALUES ('Alexandru Pavel', '35', '9', 'alexandru.pavel@outlook.com', '785012345');
INSERT INTO trainer (name, age, experience_years, email, contact_number) VALUES ('Irina Mihai', '29', '20', 'irina.mihai@yahoo.com', '796123456');
INSERT INTO trainer (name, age, experience_years, email, contact_number) VALUES ('Octavian Stanescu', '30', '12', 'octavian.stanescu@gmail.com', '707234567');
INSERT INTO trainer (name, age, experience_years, email, contact_number) VALUES ('Iulia Georgescu', '45', '15', 'iulia.georgescu@hotmail.com', '718345678');
INSERT INTO trainer (name, age, experience_years, email, contact_number) VALUES ('Adrian Diaconu', '40', '10', 'adrian.diaconu@gmail.com', '729456789');
INSERT INTO trainer (name, age, experience_years, email, contact_number) VALUES ('Elena Popescu', '35', '25', 'elena.popescu@yahoo.com', '730567890');
INSERT INTO trainer (name, age, experience_years, email, contact_number) VALUES ('Victor Ionescu', '50', '20', 'victor.ionescu@outlook.com', '741678901');

-- table 4 - members
INSERT INTO members (name, age, email, contact_number, join_date) VALUES ('Agrisan Andreea', '21', 'agrisan.andreea02@e-uvt.ro', '753777532', '21.01.2024');
INSERT INTO members (name, age, email, contact_number, join_date) VALUES ('Balaban Andrei', '28', 'balaban.andrei@gmail.com', '725123456', '12.03.2019');
INSERT INTO members (name, age, email, contact_number, join_date) VALUES ('Cristea Ana', '42', 'cristea.ana@outlook.com', '736234567', '05.09.2016');
INSERT INTO members (name, age, email, contact_number, join_date) VALUES ('Dumitru Ionel', '36', 'dumitru.ionel@yahoo.com', '747345678', '19.12.2015');
INSERT INTO members (name, age, email, contact_number, join_date) VALUES ('Enache Elena', '25', 'enache.elena@gmail.com', '758456789', '30.07.2018');
INSERT INTO members (name, age, email, contact_number, join_date) VALUES ('Florean Ioana', '31', 'florean.ioana@e-uvt.ro', '769567890', '17.06.2017');
INSERT INTO members (name, age, email, contact_number, join_date) VALUES ('Gheorghiu Vlad', '19', 'gheorghiu.vlad@blacklight.com', '770678901', '22.08.2020');
INSERT INTO members (name, age, email, contact_number, join_date) VALUES ('Hanganu Adriana', '37', 'hang.anu@outlook.com', '781789012', '14.11.2014');
INSERT INTO members (name, age, email, contact_number, join_date) VALUES ('Ionescu Stefan', '29', 'ionescu.stefan@gmail.com', '792890123', '03.05.2013');
INSERT INTO members (name, age, email, contact_number, join_date) VALUES ('Jianu Mihaela', '22', 'jianu.mihaela@yahoo.com', '703901234', '28.01.2011');
INSERT INTO members (name, age, email, contact_number, join_date) VALUES ('Kovacs Adrian', '45', 'kovacs.adrian@hotmail.com', '714012345', '09.04.2012');
INSERT INTO members (name, age, email, contact_number, join_date) VALUES ('Lupescu Elena', '20', 'lupescu.elena@gmail.com', '725123456', '01.02.2023');
INSERT INTO members (name, age, email, contact_number, join_date) VALUES ('Muresan Florin', '32', 'muresan.florin@e-uvt.ro', '736234567', '14.10.2010');
INSERT INTO members (name, age, email, contact_number, join_date) VALUES ('Nistor Ionut', '26', 'nistor.ionut@blacklight.com', '747345678', '25.07.2015');
INSERT INTO members (name, age, email, contact_number, join_date) VALUES ('Olaru Roxana', '38', 'olaru.roxana@outlook.com', '758456789', '18.09.2016');
INSERT INTO members (name, age, email, contact_number, join_date) VALUES ('Pintea Gabriel', '18', 'pintea.gabriel@gmail.com', '769567890', '02.12.2019');
INSERT INTO members (name, age, email, contact_number, join_date) VALUES ('Radulescu Andreea', '27', 'radulescu.andreea@yahoo.com', '770678901', '11.05.2014');
INSERT INTO members (name, age, email, contact_number, join_date) VALUES ('Serban Razvan', '33', 'serban.razvan@e-uvt.ro', '781789012', '24.08.2011');
INSERT INTO members (name, age, email, contact_number, join_date) VALUES ('Tudor Iulia', '23', 'tudor.iulia@hotmail.com', '792890123', '07.03.2017');
INSERT INTO members (name, age, email, contact_number, join_date) VALUES ('Ursu Paul', '43', 'ursu.paul@gmail.com', '703901234', '15.06.2012');
INSERT INTO members (name, age, email, contact_number, join_date) VALUES ('Vasilescu Alina', '21', 'vasilescu.alina@yahoo.com', '714012345', '29.01.2018');
INSERT INTO members (name, age, email, contact_number, join_date) VALUES ('Baciu Radu', '46', 'baciu.radu@blacklight.com', '725123456', '08.02.2015');
INSERT INTO members (name, age, email, contact_number, join_date) VALUES ('Cazacu Oana', '28', 'cazacu.oana@hotmail.com', '736234567', '21.05.2019');
INSERT INTO members (name, age, email, contact_number, join_date) VALUES ('Dinu Cristian', '39', 'dinu.cristian@gmail.com', '747345678', '03.09.2013');
INSERT INTO members (name, age, email, contact_number, join_date) VALUES ('Eftimie Roxana', '19', 'eftimie.roxana@yahoo.com', '758456789', '16.11.2016');
INSERT INTO members (name, age, email, contact_number, join_date) VALUES ('Fodor Andrei', '34', 'fodor.andrei@outlook.com', '769567890', '29.04.2018');
INSERT INTO members (name, age, email, contact_number, join_date) VALUES ('Gavriluta Gabriela', '24', 'gavriluta.gabriela@gmail.com', '770678901', '12.07.2014');
INSERT INTO members (name, age, email, contact_number, join_date) VALUES ('Huluba Victor', '40', 'huluba.victor@e-uvt.ro', '781789012', '25.10.2011');
INSERT INTO members (name, age, email, contact_number, join_date) VALUES ('Iacob Anca', '30', 'iacob.anca@hotmail.com', '792890123', '07.03.2017');
INSERT INTO members (name, age, email, contact_number, join_date) VALUES ('Juganaru Daniel', '20', 'juganaru.daniel@gmail.com', '703901234', '19.06.2020');
INSERT INTO members (name, age, email, contact_number, join_date) VALUES ('Keresztes Bianca', '35', 'keresztes.bianca@outlook.com', '714012345', '02.09.2015');
INSERT INTO members (name, age, email, contact_number, join_date) VALUES ('Lazar Adrian', '29', 'lazar.adrian@yahoo.com', '725123456', '14.12.2012');
INSERT INTO members (name, age, email, contact_number, join_date) VALUES ('Manciu Elena', '18', 'manciu.elena@gmail.com', '736234567', '27.02.2018');
INSERT INTO members (name, age, email, contact_number, join_date) VALUES ('Nica Mihai', '31', 'nica.mihai@blacklight.com', '747345678', '10.05.2013');
INSERT INTO members (name, age, email, contact_number, join_date) VALUES ('Olaru Maria', '21', 'olaru.maria@yahoo.com', '758456789', '23.08.2016');
INSERT INTO members (name, age, email, contact_number, join_date) VALUES ('Pavalache Ionut', '36', 'pavalache.ionut@gmail.com', '769567890', '05.11.2014');
INSERT INTO members (name, age, email, contact_number, join_date) VALUES ('Radulescu Roxana', '22', 'radulescu.roxana@outlook.com', '770678901', '18.02.2017');
INSERT INTO members (name, age, email, contact_number, join_date) VALUES ('Serban Vasile', '37', 'serban.vasile@e-uvt.ro', '781789012', '02.05.2011');
INSERT INTO members (name, age, email, contact_number, join_date) VALUES ('Tudose Mihaela', '23', 'tudose.mihaela@hotmail.com', '792890123', '15.08.2015');
INSERT INTO members (name, age, email, contact_number, join_date) VALUES ('Ursache Robert', '33', 'ursache.robert@gmail.com', '703901234', '28.11.2019');
INSERT INTO members (name, age, email, contact_number, join_date) VALUES ('Radu Florin', '31', 'radu.florin@gmail.com', '714012345', '15.12.2017');
INSERT INTO members (name, age, email, contact_number, join_date) VALUES ('Sava George', '50', 'sava.george@outlook.com', '725123456', '28.04.2016');
INSERT INTO members (name, age, email, contact_number, join_date) VALUES ('Tudor Irina', '32', 'tudor.irina@yahoo.com', '736234567', '10.08.2011');
INSERT INTO members (name, age, email, contact_number, join_date) VALUES ('Ungureanu Radu', '51', 'ungureanu.radu@e-uvt.ro', '747345678', '23.01.2020');
INSERT INTO members (name, age, email, contact_number, join_date) VALUES ('Vasilescu Elena', '19', 'vasilescu.elena@gmail.com', '758456789', '05.05.2013');
INSERT INTO members (name, age, email, contact_number, join_date) VALUES ('Xenopol Alexandru', '33', 'xenopol.alex@yahoo.com', '769567890', '18.09.2018');
INSERT INTO members (name, age, email, contact_number, join_date) VALUES ('Iancu Roxana', '52', 'iancu.roxana@hotmail.com', '770678901', '01.02.2015');
INSERT INTO members (name, age, email, contact_number, join_date) VALUES ('Zaharia Marius', '20', 'zaharia.marius@gmail.com', '781789012', '14.06.2019');
INSERT INTO members (name, age, email, contact_number, join_date) VALUES ('Antonescu Ana', '34', 'antonescu.ana@yahoo.com', '792890123', '27.10.2016');
INSERT INTO members (name, age, email, contact_number, join_date) VALUES ('Balan Ionut', '53', 'balan.ionut@e-uvt.ro', '703901234', '09.03.2014');

-- table 5 - classes
INSERT INTO classes (name, schedule, capacity, trainer_id) VALUES ('Military Training', 'Every moday from 16:00 to 17:00', '30','1');
INSERT INTO classes (name, schedule, capacity, trainer_id) VALUES ('Cardio Blast', 'Every Monday from 08:30 to 10:00', '30', '2');
INSERT INTO classes (name, schedule, capacity, trainer_id) VALUES ('Yoga Flow', 'Every Tuesday from 14:00 to 15:30', '25', '3');
INSERT INTO classes (name, schedule, capacity, trainer_id) VALUES ('Spin Cycle', 'Every Wednesday from 09:00 to 10:30', '35', '4');
INSERT INTO classes (name, schedule, capacity, trainer_id) VALUES ('HIIT Intensity', 'Every Thursday from 16:30 to 17:30', '20', '5');
INSERT INTO classes (name, schedule, capacity, trainer_id) VALUES ('Zumba Party', 'Every Friday from 13:00 to 15:00', '40', '6');
INSERT INTO classes (name, schedule, capacity, trainer_id) VALUES ('Pilates Core', 'Every Saturday from 11:30 to 12:30', '30', '7');
INSERT INTO classes (name, schedule, capacity, trainer_id) VALUES ('Kickboxing Fusion', 'Every Sunday from 18:00 to 19:30', '25', '8');
INSERT INTO classes (name, schedule, capacity, trainer_id) VALUES ('Powerlifting Basics', 'Every Monday from 15:30 to 17:00', '35', '9');
INSERT INTO classes (name, schedule, capacity, trainer_id) VALUES ('Aerobic Dance', 'Every Tuesday from 08:00 to 09:30', '20', '10');
INSERT INTO classes (name, schedule, capacity, trainer_id) VALUES ('Strength Training', 'Every Wednesday from 17:30 to 19:00', '30', '11');
INSERT INTO classes (name, schedule, capacity, trainer_id) VALUES ('Meditation Session', 'Every Thursday from 10:00 to 11:30', '25', '12');
INSERT INTO classes (name, schedule, capacity, trainer_id) VALUES ('Functional Fitness', 'Every Friday from 11:30 to 13:00', '40', '13');
INSERT INTO classes (name, schedule, capacity, trainer_id) VALUES ('Barre Sculpt', 'Every Saturday from 14:30 to 16:00', '30', '14');
INSERT INTO classes (name, schedule, capacity, trainer_id) VALUES ('Boxing Basics', 'Every Sunday from 16:00 to 17:30', '35', '15');
INSERT INTO classes (name, schedule, capacity, trainer_id) VALUES ('Circuit Training', 'Every Monday from 08:30 to 10:00', '20', '16');
INSERT INTO classes (name, schedule, capacity, trainer_id) VALUES ('Flexibility Flow', 'Every Tuesday from 15:30 to 17:00', '30', '17');
INSERT INTO classes (name, schedule, capacity, trainer_id) VALUES ('Total Body Burn', 'Every Wednesday from 19:00 to 20:30', '25', '18');
INSERT INTO classes (name, schedule, capacity, trainer_id) VALUES ('SwimFit Challenge', 'Every Thursday from 13:00 to 14:30', '40', '19');
INSERT INTO classes (name, schedule, capacity, trainer_id) VALUES ('Cycling Adventure', 'Every Friday from 14:30 to 16:00', '35', '20');
INSERT INTO classes (name, schedule, capacity, trainer_id) VALUES ('Yoga Harmony', 'Every Saturday from 08:00 to 09:30', '20', '21');
INSERT INTO classes (name, schedule, capacity, trainer_id) VALUES ('Bodyweight Sculpt', 'Every Sunday from 12:00 to 13:30', '30', '22');
INSERT INTO classes (name, schedule, capacity, trainer_id) VALUES ('Pump and Burn', 'Every Monday from 10:30 to 12:00', '25', '23');
INSERT INTO classes (name, schedule, capacity, trainer_id) VALUES ('CrossFit Challenge', 'Every Tuesday from 17:00 to 18:30', '35', '24');
INSERT INTO classes (name, schedule, capacity, trainer_id) VALUES ('Dance Fusion', 'Every Wednesday from 13:30 to 15:00', '20', '25');
INSERT INTO classes (name, schedule, capacity, trainer_id) VALUES ('Mindful Stretch', 'Every Thursday from 11:00 to 12:30', '30', '26');
INSERT INTO classes (name, schedule, capacity, trainer_id) VALUES ('Core Blast', 'Every Friday from 18:30 to 20:00', '40', '27');
INSERT INTO classes (name, schedule, capacity, trainer_id) VALUES ('Functional Movement', 'Every Saturday from 09:30 to 11:00', '35', '28');
INSERT INTO classes (name, schedule, capacity, trainer_id) VALUES ('TRX Total Body', 'Every Sunday from 14:00 to 15:30', '30', '29');
INSERT INTO classes (name, schedule, capacity, trainer_id) VALUES ('Plyometric Power', 'Every Monday from 15:00 to 16:30', '25', '30');
INSERT INTO classes (name, schedule, capacity, trainer_id) VALUES ('Balance and Flex', 'Every Tuesday from 08:30 to 10:00', '35', '31');
INSERT INTO classes (name, schedule, capacity, trainer_id) VALUES ('Bootcamp Challenge', 'Every Wednesday from 16:00 to 17:30', '20', '32');
INSERT INTO classes (name, schedule, capacity, trainer_id) VALUES ('HIIT Express', 'Every Monday from 08:00 to 09:30', '50', '33');
INSERT INTO classes (name, schedule, capacity, trainer_id) VALUES ('Yoga Flow', 'Every Tuesday from 14:00 to 15:30', '70', '34');
INSERT INTO classes (name, schedule, capacity, trainer_id) VALUES ('Spin Cycling', 'Every Wednesday from 18:30 to 20:00', '80', '35');
INSERT INTO classes (name, schedule, capacity, trainer_id) VALUES ('Zumba Party', 'Every Thursday from 12:00 to 13:30', '90', '36');
INSERT INTO classes (name, schedule, capacity, trainer_id) VALUES ('Kettlebell Mastery', 'Every Friday from 16:00 to 17:30', '60', '37');
INSERT INTO classes (name, schedule, capacity, trainer_id) VALUES ('Cardio Kickboxing', 'Every Saturday from 10:30 to 12:00', '100', '38');
INSERT INTO classes (name, schedule, capacity, trainer_id) VALUES ('BodyCombat', 'Every Sunday from 17:00 to 18:30', '45', '39');
INSERT INTO classes (name, schedule, capacity, trainer_id) VALUES ('Pilates Fusion', 'Every Monday from 10:30 to 12:00', '55', '40');
INSERT INTO classes (name, schedule, capacity, trainer_id) VALUES ('Strength Training', 'Every Tuesday from 16:00 to 17:30', '75', '41');
INSERT INTO classes (name, schedule, capacity, trainer_id) VALUES ('Aqua Aerobics', 'Every Wednesday from 11:30 to 13:00', '85', '42');
INSERT INTO classes (name, schedule, capacity, trainer_id) VALUES ('Functional Fitness', 'Every Thursday from 14:00 to 15:30', '65', '43');
INSERT INTO classes (name, schedule, capacity, trainer_id) VALUES ('CrossFit Challenge', 'Every Tuesday from 08:30 to 10:00', '55', '44');
INSERT INTO classes (name, schedule, capacity, trainer_id) VALUES ('Prenatal Yoga', 'Every Friday from 13:30 to 15:00', '40', '45');
INSERT INTO classes (name, schedule, capacity, trainer_id) VALUES ('TRX Suspension', 'Every Sunday from 10:00 to 11:30', '90', '46');
INSERT INTO classes (name, schedule, capacity, trainer_id) VALUES ('Barre Sculpt', 'Every Wednesday from 19:00 to 20:30', '75', '47');
INSERT INTO classes (name, schedule, capacity, trainer_id) VALUES ('Tabata Training', 'Every Monday from 15:30 to 17:00', '80', '48');
INSERT INTO classes (name, schedule, capacity, trainer_id) VALUES ('Meditation Session', 'Every Saturday from 08:00 to 09:30', '50', '49');
INSERT INTO classes (name, schedule, capacity, trainer_id) VALUES ('Senior Fitness', 'Every Tuesday from 13:00 to 14:30', '30', '50');

-- table 6 - members_goals
INSERT INTO members_goals (member_id, goal_name) VALUES ('1', 'Losing weight');
INSERT INTO members_goals (member_id, goal_name) VALUES ('2', 'Building muscle');
INSERT INTO members_goals (member_id, goal_name) VALUES ('3', 'Improving flexibility');
INSERT INTO members_goals (member_id, goal_name) VALUES ('4', 'Cardiovascular fitness');
INSERT INTO members_goals (member_id, goal_name) VALUES ('5', 'Stress relief');
INSERT INTO members_goals (member_id, goal_name) VALUES ('6', 'Enhancing endurance');
INSERT INTO members_goals (member_id, goal_name) VALUES ('7', 'Toning and sculpting');
INSERT INTO members_goals (member_id, goal_name) VALUES ('8', 'Sports-specific training');
INSERT INTO members_goals (member_id, goal_name) VALUES ('9', 'Rehabilitation and injury prevention');
INSERT INTO members_goals (member_id, goal_name) VALUES ('10', 'Group fitness participation');
INSERT INTO members_goals (member_id, goal_name) VALUES ('11', 'Maintaining overall health');
INSERT INTO members_goals (member_id, goal_name) VALUES ('12', 'Boosting energy levels');
INSERT INTO members_goals (member_id, goal_name) VALUES ('13', 'Social interaction');
INSERT INTO members_goals (member_id, goal_name) VALUES ('14', 'Improving balance');
INSERT INTO members_goals (member_id, goal_name) VALUES ('15', 'Specific event preparation');
INSERT INTO members_goals (member_id, goal_name) VALUES ('16', 'Posture improvement');
INSERT INTO members_goals (member_id, goal_name) VALUES ('17', 'Mind-body connection');
INSERT INTO members_goals (member_id, goal_name) VALUES ('18', 'Healthy lifestyle adoption');
INSERT INTO members_goals (member_id, goal_name) VALUES ('19', 'Weight maintenance');
INSERT INTO members_goals (member_id, goal_name) VALUES ('20', 'Boosting self-esteem');
INSERT INTO members_goals (member_id, goal_name) VALUES ('21', 'Enhancing athletic performance');
INSERT INTO members_goals (member_id, goal_name) VALUES ('22', 'Managing chronic conditions');
INSERT INTO members_goals (member_id, goal_name) VALUES ('23', 'Improving sleep quality');
INSERT INTO members_goals (member_id, goal_name) VALUES ('24', 'Nutritional awareness');
INSERT INTO members_goals (member_id, goal_name) VALUES ('25', 'Mindfulness and relaxation');
INSERT INTO members_goals (member_id, goal_name) VALUES ('26', 'Joint health and mobility');
INSERT INTO members_goals (member_id, goal_name) VALUES ('27', 'Weightlifting proficiency');
INSERT INTO members_goals (member_id, goal_name) VALUES ('28', 'Increasing agility');
INSERT INTO members_goals (member_id, goal_name) VALUES ('29', 'Participating in competitions');
INSERT INTO members_goals (member_id, goal_name) VALUES ('30', 'Building core strength');
INSERT INTO members_goals (member_id, goal_name) VALUES ('31', 'Circuit training mastery');
INSERT INTO members_goals (member_id, goal_name) VALUES ('32', 'Enhancing coordination');
INSERT INTO members_goals (member_id, goal_name) VALUES ('33', 'High-intensity interval training (HIIT)');
INSERT INTO members_goals (member_id, goal_name) VALUES ('34', 'Family fitness');
INSERT INTO members_goals (member_id, goal_name) VALUES ('35', 'Outdoor fitness activities');
INSERT INTO members_goals (member_id, goal_name) VALUES ('36', 'Postpartum recovery');
INSERT INTO members_goals (member_id, goal_name) VALUES ('37', 'Increasing metabolism');
INSERT INTO members_goals (member_id, goal_name) VALUES ('38', 'Improving digestion');
INSERT INTO members_goals (member_id, goal_name) VALUES ('39', 'Building lean muscle mass');
INSERT INTO members_goals (member_id, goal_name) VALUES ('40', 'Mindful eating habits');
INSERT INTO members_goals (member_id, goal_name) VALUES ('41', 'Preventing osteoporosis');
INSERT INTO members_goals (member_id, goal_name) VALUES ('42', 'Enhancing immune function');
INSERT INTO members_goals (member_id, goal_name) VALUES ('43', 'Reducing back pain');
INSERT INTO members_goals (member_id, goal_name) VALUES ('44', 'Balancing work and fitness');
INSERT INTO members_goals (member_id, goal_name) VALUES ('45', 'Increasing self-discipline');
INSERT INTO members_goals (member_id, goal_name) VALUES ('46', 'Alleviating anxiety');
INSERT INTO members_goals (member_id, goal_name) VALUES ('47', 'Promoting heart health');
INSERT INTO members_goals (member_id, goal_name) VALUES ('48', 'Improving body composition');
INSERT INTO members_goals (member_id, goal_name) VALUES ('49', 'Enhancing mental clarity');
INSERT INTO members_goals (member_id, goal_name) VALUES ('50', 'Developing a workout routine');

-- table 7 - workout_plans
INSERT INTO workout_plans (member_id, name) VALUES ('1', 'Full Body Strenght');
INSERT INTO workout_plans (member_id, name) VALUES ('2', 'Cardio Blast');
INSERT INTO workout_plans (member_id, name) VALUES ('3', 'Flexibility Focus');
INSERT INTO workout_plans (member_id, name) VALUES ('4', 'High-Intensity Interval Training (HIIT)');
INSERT INTO workout_plans (member_id, name) VALUES ('5', 'Core Conditioning');
INSERT INTO workout_plans (member_id, name) VALUES ('6', 'Strength and Power');
INSERT INTO workout_plans (member_id, name) VALUES ('7', 'Endurance Builder');
INSERT INTO workout_plans (member_id, name) VALUES ('8', 'Functional Fitness');
INSERT INTO workout_plans (member_id, name) VALUES ('9', 'Total Body Sculpt');
INSERT INTO workout_plans (member_id, name) VALUES ('10', 'Yoga Journey');
INSERT INTO workout_plans (member_id, name) VALUES ('11', 'Pilates Perfection');
INSERT INTO workout_plans (member_id, name) VALUES ('12', 'CrossFit Challenge');
INSERT INTO workout_plans (member_id, name) VALUES ('13', 'Mindful Movement');
INSERT INTO workout_plans (member_id, name) VALUES ('14', 'Weight Loss Circuit');
INSERT INTO workout_plans (member_id, name) VALUES ('15', 'Bodyweight Basics');
INSERT INTO workout_plans (member_id, name) VALUES ('16', 'Outdoor Adventure Fitness');
INSERT INTO workout_plans (member_id, name) VALUES ('17', 'Sprint Training');
INSERT INTO workout_plans (member_id, name) VALUES ('18', 'Swimming for Fitness');
INSERT INTO workout_plans (member_id, name) VALUES ('19', 'Kettlebell Mastery');
INSERT INTO workout_plans (member_id, name) VALUES ('20', 'Zumba Fun');
INSERT INTO workout_plans (member_id, name) VALUES ('21', 'Bodybuilding Blueprint');
INSERT INTO workout_plans (member_id, name) VALUES ('22', 'Kickboxing Intensity');
INSERT INTO workout_plans (member_id, name) VALUES ('23', 'Stair Climbing Challenge');
INSERT INTO workout_plans (member_id, name) VALUES ('24', 'Meditation and Movement');
INSERT INTO workout_plans (member_id, name) VALUES ('25', 'Cycling Adventure');
INSERT INTO workout_plans (member_id, name) VALUES ('26', 'Dance Fusion');
INSERT INTO workout_plans (member_id, name) VALUES ('27', 'Strength Training for Seniors');
INSERT INTO workout_plans (member_id, name) VALUES ('28', 'Barre Sculpt');
INSERT INTO workout_plans (member_id, name) VALUES ('29', 'Functional Mobility');
INSERT INTO workout_plans (member_id, name) VALUES ('30', 'Parkour Challenge');
INSERT INTO workout_plans (member_id, name) VALUES ('31', 'Martial Arts Mastery');
INSERT INTO workout_plans (member_id, name) VALUES ('32', 'Climbing Adventure');
INSERT INTO workout_plans (member_id, name) VALUES ('33', 'TRX Total Body');
INSERT INTO workout_plans (member_id, name) VALUES ('34', 'Rowing Regimen');
INSERT INTO workout_plans (member_id, name) VALUES ('35', 'Soccer Fitness');
INSERT INTO workout_plans (member_id, name) VALUES ('36', 'Surfing Strength');
INSERT INTO workout_plans (member_id, name) VALUES ('37', 'Paddleboarding Workout');
INSERT INTO workout_plans (member_id, name) VALUES ('38', 'Golf Conditioning');
INSERT INTO workout_plans (member_id, name) VALUES ('39', 'Skiing Stamina');
INSERT INTO workout_plans (member_id, name) VALUES ('40', 'Prenatal Fitness');
INSERT INTO workout_plans (member_id, name) VALUES ('41', 'Postpartum Recovery');
INSERT INTO workout_plans (member_id, name) VALUES ('42', 'Active Aging Program');
INSERT INTO workout_plans (member_id, name) VALUES ('43', 'Team Sports Training');
INSERT INTO workout_plans (member_id, name) VALUES ('44', 'Aerobic Dance Party');
INSERT INTO workout_plans (member_id, name) VALUES ('45', 'Functional Strength for Runners');
INSERT INTO workout_plans (member_id, name) VALUES ('46', 'Gymnastics Foundations');
INSERT INTO workout_plans (member_id, name) VALUES ('47', 'Body and Mind Harmony');
INSERT INTO workout_plans (member_id, name) VALUES ('48', 'Boxing Bootcamp');
INSERT INTO workout_plans (member_id, name) VALUES ('49', 'Tennis Conditioning');
INSERT INTO workout_plans (member_id, name) VALUES ('50', 'Holistic Wellness Journey');

-- table 8 - subscriptions
INSERT INTO subscriptions (gym_id, member_id, issue_date, end_date, active, amount_ron) VALUES ('1','1','21.01.2024','21.02.2024','Y','189');
INSERT INTO subscriptions (gym_id, member_id, issue_date, end_date, active, amount_ron) VALUES ('2','2','12.03.2023','12.03.2024','Y','1000');
INSERT INTO subscriptions (gym_id, member_id, issue_date, end_date, active, amount_ron) VALUES ('3','3','05.09.2023','05.10.2023','N','189');
INSERT INTO subscriptions (gym_id, member_id, issue_date, end_date, active, amount_ron) VALUES ('4','4','19.12.2023','19.01.2024','N','1000');
INSERT INTO subscriptions (gym_id, member_id, issue_date, end_date, active, amount_ron) VALUES ('5','5','30.07.2023','30.08.2023','N','189');
INSERT INTO subscriptions (gym_id, member_id, issue_date, end_date, active, amount_ron) VALUES ('6','6','17.06.2023','17.07.2023','N','189');
INSERT INTO subscriptions (gym_id, member_id, issue_date, end_date, active, amount_ron) VALUES ('7','7','22.08.2023','22.09.2023','N','189');
INSERT INTO subscriptions (gym_id, member_id, issue_date, end_date, active, amount_ron) VALUES ('8','8','14.11.2023','14.12.2023','N','189');
INSERT INTO subscriptions (gym_id, member_id, issue_date, end_date, active, amount_ron) VALUES ('9','9','03.05.2023','03.06.2023','N','189');
INSERT INTO subscriptions (gym_id, member_id, issue_date, end_date, active, amount_ron) VALUES ('10','10','28.02.2023','28.02.2024','Y','1000');
INSERT INTO subscriptions (gym_id, member_id, issue_date, end_date, active, amount_ron) VALUES ('11','11','09.04.2023','09.05.2023','N','189');
INSERT INTO subscriptions (gym_id, member_id, issue_date, end_date, active, amount_ron) VALUES ('12','12','01.03.2023','01.03.2024','Y','1000');
INSERT INTO subscriptions (gym_id, member_id, issue_date, end_date, active, amount_ron) VALUES ('13','13','14.11.2023','14.11.2024','Y','1000');
INSERT INTO subscriptions (gym_id, member_id, issue_date, end_date, active, amount_ron) VALUES ('14','14','25.08.2023','25.08.2024','Y','1000');
INSERT INTO subscriptions (gym_id, member_id, issue_date, end_date, active, amount_ron) VALUES ('15','15','18.09.2023','18.09.2024','Y','1000');
INSERT INTO subscriptions (gym_id, member_id, issue_date, end_date, active, amount_ron) VALUES ('16','16','02.12.2023','02.01.2024','N','189');
INSERT INTO subscriptions (gym_id, member_id, issue_date, end_date, active, amount_ron) VALUES ('17','17','11.05.2023','11.06.2023','N','189');
INSERT INTO subscriptions (gym_id, member_id, issue_date, end_date, active, amount_ron) VALUES ('18','18','24.08.2023','24.09.2023','N','189');
INSERT INTO subscriptions (gym_id, member_id, issue_date, end_date, active, amount_ron) VALUES ('19','19','07.03.2023','07.04.2023','N','189');
INSERT INTO subscriptions (gym_id, member_id, issue_date, end_date, active, amount_ron) VALUES ('20','20','15.06.2023','15.07.2023','N','189');
INSERT INTO subscriptions (gym_id, member_id, issue_date, end_date, active, amount_ron) VALUES ('21','21','21.05.2023','21.06.2023','N','189');
INSERT INTO subscriptions (gym_id, member_id, issue_date, end_date, active, amount_ron) VALUES ('22','22','29.04.2023','29.05.2023','N','189');
INSERT INTO subscriptions (gym_id, member_id, issue_date, end_date, active, amount_ron) VALUES ('23','23','10.08.2023','10.09.2023','N','189');
INSERT INTO subscriptions (gym_id, member_id, issue_date, end_date, active, amount_ron) VALUES ('24','24','23.01.2023','23.01.2024','Y','1000');
INSERT INTO subscriptions (gym_id, member_id, issue_date, end_date, active, amount_ron) VALUES ('25','25','05.05.2023','05.06.2023','N','189');
INSERT INTO subscriptions (gym_id, member_id, issue_date, end_date, active, amount_ron) VALUES ('26','26','18.09.2023','18.10.2023','N','189');
INSERT INTO subscriptions (gym_id, member_id, issue_date, end_date, active, amount_ron) VALUES ('27','27','28.04.2023','28.05.2023','N','189');
INSERT INTO subscriptions (gym_id, member_id, issue_date, end_date, active, amount_ron) VALUES ('28','28','10.03.2023','10.04.2023','N','189');
INSERT INTO subscriptions (gym_id, member_id, issue_date, end_date, active, amount_ron) VALUES ('29','29','27.11.2023','27.11.2024','Y','1000');
INSERT INTO subscriptions (gym_id, member_id, issue_date, end_date, active, amount_ron) VALUES ('30','30','21.05.2023','21.06.2023','N','189');
INSERT INTO subscriptions (gym_id, member_id, issue_date, end_date, active, amount_ron) VALUES ('31','31','10.08.2023','10.09.2023','N','189');
INSERT INTO subscriptions (gym_id, member_id, issue_date, end_date, active, amount_ron) VALUES ('32','32','23.01.2023','23.01.2024','Y','1000');
INSERT INTO subscriptions (gym_id, member_id, issue_date, end_date, active, amount_ron) VALUES ('33','33','05.05.2023','05.06.2023','N','189');
INSERT INTO subscriptions (gym_id, member_id, issue_date, end_date, active, amount_ron) VALUES ('34','34','18.09.2023','18.10.2023','N','189');
INSERT INTO subscriptions (gym_id, member_id, issue_date, end_date, active, amount_ron) VALUES ('35','35','28.04.2023','28.05.2023','N','189');
INSERT INTO subscriptions (gym_id, member_id, issue_date, end_date, active, amount_ron) VALUES ('36','36','10.03.2023','10.04.2023','N','189');
INSERT INTO subscriptions (gym_id, member_id, issue_date, end_date, active, amount_ron) VALUES ('37','37','27.11.2023','27.11.2024','Y','1000');
INSERT INTO subscriptions (gym_id, member_id, issue_date, end_date, active, amount_ron) VALUES ('38','38','14.01.2024','14.02.2024','Y','189');
INSERT INTO subscriptions (gym_id, member_id, issue_date, end_date, active, amount_ron) VALUES ('39','39','06.06.2023','06.07.2023','N','189');
INSERT INTO subscriptions (gym_id, member_id, issue_date, end_date, active, amount_ron) VALUES ('40','40','19.09.2023','19.10.2023','N','189');
INSERT INTO subscriptions (gym_id, member_id, issue_date, end_date, active, amount_ron) VALUES ('41','41','01.05.2023','01.05.2024','Y','1000');
INSERT INTO subscriptions (gym_id, member_id, issue_date, end_date, active, amount_ron) VALUES ('42','42','14.03.2023','14.04.2023','N','189');
INSERT INTO subscriptions (gym_id, member_id, issue_date, end_date, active, amount_ron) VALUES ('43','43','26.10.2023','26.11.2023','N','189');
INSERT INTO subscriptions (gym_id, member_id, issue_date, end_date, active, amount_ron) VALUES ('44','44','03.08.2023','03.09.2023','N','189');
INSERT INTO subscriptions (gym_id, member_id, issue_date, end_date, active, amount_ron) VALUES ('45','45','11.12.2023','11.01.2024','N','189');
INSERT INTO subscriptions (gym_id, member_id, issue_date, end_date, active, amount_ron) VALUES ('46','46','22.02.2023','22.03.2023','N','189');
INSERT INTO subscriptions (gym_id, member_id, issue_date, end_date, active, amount_ron) VALUES ('47','47','30.07.2023','30.08.2023','N','189');
INSERT INTO subscriptions (gym_id, member_id, issue_date, end_date, active, amount_ron) VALUES ('48','48','17.06.2023','17.07.2023','N','189');
INSERT INTO subscriptions (gym_id, member_id, issue_date, end_date, active, amount_ron) VALUES ('49','49','22.08.2023','22.09.2023','N','189');
INSERT INTO subscriptions (gym_id, member_id, issue_date, end_date, active, amount_ron) VALUES ('50','50','05.11.2023','05.12.2023','N','189');

-- table 9 - equipment
INSERT INTO equipment (name, quantity, condition) VALUES ('Treadmill', '10', 'Good');
INSERT INTO equipment (name, quantity, condition) VALUES ('Dumbbells', '50', 'Excellent');
INSERT INTO equipment (name, quantity, condition) VALUES ('Elliptical Trainer', '5', 'Fair');
INSERT INTO equipment (name, quantity, condition) VALUES ('Weight Bench', '20', 'Excellent');
INSERT INTO equipment (name, quantity, condition) VALUES ('Stationary Bike', '8', 'Good');
INSERT INTO equipment (name, quantity, condition) VALUES ('Barbells', '30', 'Fair');
INSERT INTO equipment (name, quantity, condition) VALUES ('Rowing Machine', '7', 'Good');
INSERT INTO equipment (name, quantity, condition) VALUES ('Leg Press Machine', '3', 'Good');
INSERT INTO equipment (name, quantity, condition) VALUES ('Pull-up Bar', '15', 'Excellent');
INSERT INTO equipment (name, quantity, condition) VALUES ('Exercise Ball', '25', 'Fair');
INSERT INTO equipment (name, quantity, condition) VALUES ('Stair Climber', '10', 'Good');
INSERT INTO equipment (name, quantity, condition) VALUES ('Resistance Bands', '15', 'Excellent');
INSERT INTO equipment (name, quantity, condition) VALUES ('Yoga Blocks', '8', 'Fair');
INSERT INTO equipment (name, quantity, condition) VALUES ('Plyo Boxes', '20', 'Excellent');
INSERT INTO equipment (name, quantity, condition) VALUES ('Kettlebells', '10', 'Good');
INSERT INTO equipment (name, quantity, condition) VALUES ('Jump Ropes', '25', 'Fair');
INSERT INTO equipment (name, quantity, condition) VALUES ('Battle Ropes', '7', 'Good');
INSERT INTO equipment (name, quantity, condition) VALUES ('Punching Bag', '5', 'Excellent');
INSERT INTO equipment (name, quantity, condition) VALUES ('Medicine Balls', '12', 'Fair');
INSERT INTO equipment (name, quantity, condition) VALUES ('TRX Suspension System', '8', 'Excellent');
INSERT INTO equipment (name, quantity, condition) VALUES ('Ab Roller', '15', 'Fair');
INSERT INTO equipment (name, quantity, condition) VALUES ('Pilates Ring', '4', 'Excellent');
INSERT INTO equipment (name, quantity, condition) VALUES ('Sled Push', '6', 'Good');
INSERT INTO equipment (name, quantity, condition) VALUES ('Agility Ladder', '10', 'Excellent');
INSERT INTO equipment (name, quantity, condition) VALUES ('Foam Rollers', '18', 'Fair');
INSERT INTO equipment (name, quantity, condition) VALUES ('Boxing Gloves', '10', 'Good');
INSERT INTO equipment (name, quantity, condition) VALUES ('Bosu Ball', '7', 'Excellent');
INSERT INTO equipment (name, quantity, condition) VALUES ('Dip Station', '3', 'Good');
INSERT INTO equipment (name, quantity, condition) VALUES ('Resistance Tubes', '20', 'Fair');
INSERT INTO equipment (name, quantity, condition) VALUES ('Balance Board', '5', 'Excellent');
INSERT INTO equipment (name, quantity, condition) VALUES ('Squat Rack', '10', 'Fair');
INSERT INTO equipment (name, quantity, condition) VALUES ('Calf Raise Machine', '2', 'Good');
INSERT INTO equipment (name, quantity, condition) VALUES ('Boxing Speed Bag', '5', 'Excellent');
INSERT INTO equipment (name, quantity, condition) VALUES ('Plyo Balls', '12', 'Good');
INSERT INTO equipment (name, quantity, condition) VALUES ('Foam Rolling Stick', '8', 'Fair');
INSERT INTO equipment (name, quantity, condition) VALUES ('Ankle Weights', '15', 'Excellent');
INSERT INTO equipment (name, quantity, condition) VALUES ('Gymnastic Rings', '6', 'Good');
INSERT INTO equipment (name, quantity, condition) VALUES ('Pilates Ball', '3', 'Excellent');
INSERT INTO equipment (name, quantity, condition) VALUES ('Speed Parachute', '4', 'Fair');
INSERT INTO equipment (name, quantity, condition) VALUES ('Battling Ropes', '7', 'Excellent');
INSERT INTO equipment (name, quantity, condition) VALUES ('Hand Grips', '10', 'Good');
INSERT INTO equipment (name, quantity, condition) VALUES ('Hula Hoops', '15', 'Fair');
INSERT INTO equipment (name, quantity, condition) VALUES ('Mini Bands', '20', 'Excellent');
INSERT INTO equipment (name, quantity, condition) VALUES ('Boxing Reflex Ball', '6', 'Good');
INSERT INTO equipment (name, quantity, condition) VALUES ('Foam Massage Roller', '8', 'Excellent');
INSERT INTO equipment (name, quantity, condition) VALUES ('Pilates Cadillac', '2', 'Good');
INSERT INTO equipment (name, quantity, condition) VALUES ('Aerobic Step', '10', 'Excellent');
INSERT INTO equipment (name, quantity, condition) VALUES ('Ab Wheel', '4', 'Fair');
INSERT INTO equipment (name, quantity, condition) VALUES ('Battle Ropes', '7', 'Good');
INSERT INTO equipment (name, quantity, condition) VALUES ('Punching Bag', '5', 'Excellent');

-- table 10 - feedback
INSERT INTO feedback (member_id, trainer_id, classes_id, rating, feedback_date) VALUES ('1', '1', '1', '10', '25.01.2024');
INSERT INTO feedback (member_id, trainer_id, classes_id, rating, feedback_date) VALUES ('2', '2', '2', '9', '13.04.2019');
INSERT INTO feedback (member_id, trainer_id, classes_id, rating, feedback_date) VALUES ('3', '3', '3', '8', '12.10.2016');
INSERT INTO feedback (member_id, trainer_id, classes_id, rating, feedback_date) VALUES ('4', '4', '4', '7', '22.01.2016');
INSERT INTO feedback (member_id, trainer_id, classes_id, rating, feedback_date) VALUES ('5', '5', '5', '6', '28.10.2018');
INSERT INTO feedback (member_id, trainer_id, classes_id, rating, feedback_date) VALUES ('6', '6', '6', '5', '03.08.2017');
INSERT INTO feedback (member_id, trainer_id, classes_id, rating, feedback_date) VALUES ('7', '7', '7', '9', '10.12.2020');
INSERT INTO feedback (member_id, trainer_id, classes_id, rating, feedback_date) VALUES ('8', '8', '8', '8', '04.02.2015');
INSERT INTO feedback (member_id, trainer_id, classes_id, rating, feedback_date) VALUES ('9', '9', '9', '7', '07.08.2013');
INSERT INTO feedback (member_id, trainer_id, classes_id, rating, feedback_date) VALUES ('10', '10', '10', '6', '27.02.2011');
INSERT INTO feedback (member_id, trainer_id, classes_id, rating, feedback_date) VALUES ('11', '11', '11', '10', '21.06.2012');
INSERT INTO feedback (member_id, trainer_id, classes_id, rating, feedback_date) VALUES ('12', '12', '12', '9', '02.03.2023');
INSERT INTO feedback (member_id, trainer_id, classes_id, rating, feedback_date) VALUES ('13', '13', '13', '8', '25.11.2010');
INSERT INTO feedback (member_id, trainer_id, classes_id, rating, feedback_date) VALUES ('14', '14', '14', '7', '25.02.2015');
INSERT INTO feedback (member_id, trainer_id, classes_id, rating, feedback_date) VALUES ('15', '15', '15', '6', '08.04.2016');
INSERT INTO feedback (member_id, trainer_id, classes_id, rating, feedback_date) VALUES ('16', '16', '16', '10', '21.01.2020');
INSERT INTO feedback (member_id, trainer_id, classes_id, rating, feedback_date) VALUES ('17', '17', '17', '9', '11.06.2014');
INSERT INTO feedback (member_id, trainer_id, classes_id, rating, feedback_date) VALUES ('18', '18', '18', '8', '24.09.2011');
INSERT INTO feedback (member_id, trainer_id, classes_id, rating, feedback_date) VALUES ('19', '19', '19', '7', '07.05.2017');
INSERT INTO feedback (member_id, trainer_id, classes_id, rating, feedback_date) VALUES ('20', '20', '20', '6', '19.08.2012');
INSERT INTO feedback (member_id, trainer_id, classes_id, rating, feedback_date) VALUES ('21', '21', '21', '10', '29.01.2018');
INSERT INTO feedback (member_id, trainer_id, classes_id, rating, feedback_date) VALUES ('22', '22', '22', '9', '11.02.2015');
INSERT INTO feedback (member_id, trainer_id, classes_id, rating, feedback_date) VALUES ('23', '23', '23', '8', '24.05.2019');
INSERT INTO feedback (member_id, trainer_id, classes_id, rating, feedback_date) VALUES ('24', '24', '24', '7', '05.09.2013');
INSERT INTO feedback (member_id, trainer_id, classes_id, rating, feedback_date) VALUES ('25', '25', '25', '6', '18.11.2016');
INSERT INTO feedback (member_id, trainer_id, classes_id, rating, feedback_date) VALUES ('26', '26', '26', '10', '29.04.2018');
INSERT INTO feedback (member_id, trainer_id, classes_id, rating, feedback_date) VALUES ('27', '27', '27', '9', '12.07.2014');
INSERT INTO feedback (member_id, trainer_id, classes_id, rating, feedback_date) VALUES ('28', '28', '28', '8', '25.10.2011');
INSERT INTO feedback (member_id, trainer_id, classes_id, rating, feedback_date) VALUES ('29', '29', '29', '7', '07.03.2017');
INSERT INTO feedback (member_id, trainer_id, classes_id, rating, feedback_date) VALUES ('30', '30', '30', '6', '19.06.2020');
INSERT INTO feedback (member_id, trainer_id, classes_id, rating, feedback_date) VALUES ('31', '31', '31', '10', '02.09.2015');
INSERT INTO feedback (member_id, trainer_id, classes_id, rating, feedback_date) VALUES ('32', '32', '32', '9', '14.12.2012');
INSERT INTO feedback (member_id, trainer_id, classes_id, rating, feedback_date) VALUES ('33', '33', '33', '8', '27.02.2018');
INSERT INTO feedback (member_id, trainer_id, classes_id, rating, feedback_date) VALUES ('34', '34', '34', '7', '10.05.2013');
INSERT INTO feedback (member_id, trainer_id, classes_id, rating, feedback_date) VALUES ('35', '35', '35', '6', '23.08.2016');
INSERT INTO feedback (member_id, trainer_id, classes_id, rating, feedback_date) VALUES ('36', '36', '36', '10', '05.11.2014');
INSERT INTO feedback (member_id, trainer_id, classes_id, rating, feedback_date) VALUES ('37', '37', '37', '9', '18.02.2017');
INSERT INTO feedback (member_id, trainer_id, classes_id, rating, feedback_date) VALUES ('38', '38', '38', '8', '02.05.2011');
INSERT INTO feedback (member_id, trainer_id, classes_id, rating, feedback_date) VALUES ('39', '39', '39', '7', '15.08.2015');
INSERT INTO feedback (member_id, trainer_id, classes_id, rating, feedback_date) VALUES ('40', '40', '40', '6', '28.11.2019');
INSERT INTO feedback (member_id, trainer_id, classes_id, rating, feedback_date) VALUES ('41', '41', '41', '10', '15.12.2017');
INSERT INTO feedback (member_id, trainer_id, classes_id, rating, feedback_date) VALUES ('42', '42', '42', '9', '28.04.2016');
INSERT INTO feedback (member_id, trainer_id, classes_id, rating, feedback_date) VALUES ('43', '43', '43', '8', '10.08.2011');
INSERT INTO feedback (member_id, trainer_id, classes_id, rating, feedback_date) VALUES ('44', '44', '44', '7', '23.01.2020');
INSERT INTO feedback (member_id, trainer_id, classes_id, rating, feedback_date) VALUES ('45', '45', '45', '6', '05.05.2013');
INSERT INTO feedback (member_id, trainer_id, classes_id, rating, feedback_date) VALUES ('46', '46', '46', '10', '18.09.2018');
INSERT INTO feedback (member_id, trainer_id, classes_id, rating, feedback_date) VALUES ('47', '47', '47', '9', '01.02.2015');
INSERT INTO feedback (member_id, trainer_id, classes_id, rating, feedback_date) VALUES ('48', '48', '48', '8', '14.06.2019');
INSERT INTO feedback (member_id, trainer_id, classes_id, rating, feedback_date) VALUES ('49', '49', '49', '7', '27.10.2016');
INSERT INTO feedback (member_id, trainer_id, classes_id, rating, feedback_date) VALUES ('50', '50', '50', '6', '09.03.2014');